version: '3'
services:
  xl:
    image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-devel
    container_name: xl
    volumes:
      - /home/guests/xl:/root #! 这里的路径看需要改一下，你可能用不着3个共享目录 source:target
      - /datasets:/datasets
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    ipc: host
    network_mode: host  # 需要在容器内使用网卡时开启此选项
    # ports:
    #   - "10001:22"
    # 开启 ssh 连接，确保容器内已 apt install openssh-server
    command: bash -c "apt update ; apt install -y openssh-server ; echo 'root:passwd' | chpasswd ; mkdir -p /var/run/sshd && echo 'Port 40620' >> /etc/ssh/sshd_config && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && /usr/sbin/sshd -D" #! 修改端口
    # privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu,compute,utility,graphics]
              device_ids: ["6", "7"]  # 限制可用显卡